### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by EricWVGG** [nicklockwood/layout#170]
feature request

(This thing looks wild, I'm digging in and love it so far. You should solicit a list of active projects that use this lib, more folks need to know about it)

**Comment by nicklockwood** [comment]
I'm glad you're enjoying Layout!

With respect to your feature suggestion tho, Swift Package Manager doesn't support iOS and Layout only supports iOS :-)

**Comment by EricWVGG** [comment]
lol duh. Didn't know that… I've been mostly working in the microcosm of server-side Swift for a while.

It's looking like the lack of support for SplitViewController and NavigationController might be a deal breaker after all. I'll keep on eye on this project, though. Good luck.

**Comment by tcurdt** [comment]
This should be reopened, no?

**Comment by Kaspik** [comment]
@nicklockwood Morning! SPM is now fully integrated into XCode 11, could this be reopened or implemented? :) Thanks!
