### ISSUE TITLE
Swift 5 compatibility for XCode 10.2

### ISSUE THREAD

**Issue by Kaspik** [nicklockwood/layout#171]
Good morning Nick!

Almost year later - I'm here again. :) (For reference - https://github.com/nicklockwood/layout/issues/130)

XCode 10.2 has been released officially and it includes Swift 5. It looks like Layout needs (probably just one) small update - are you aware of that and are you planning another release for Swift 5?
Thank you!
<img width="1447" alt="Screenshot 2019-03-26 at 08 36 23" src="https://user-images.githubusercontent.com/7204168/54979036-5b812f80-4fa2-11e9-973b-05ffe27dd48b.png">

**Comment by nicklockwood** [comment]
@kaspik yes, I'll be shipping a Swift 5 compatible version shortly. Thanks for the PR!

**Comment by Kaspik** [comment]
@nicklockwood It doesn't need to be compatible with swift 5 yet, but needs to be compatible with XCode 10.2 (even on Swift 4.2).

No problem! :)

**Comment by nicklockwood** [comment]
@Kaspik fixed in version 0.6.36. Thanks!
