### ISSUE TITLE
UITableView.tableHeaderView support

### ISSUE THREAD

**Issue by algrid** [nicklockwood/layout#177]
Thank you for the great library!

This is a feature request. It would be nice to support the `tableHeaderView` property of `UITableView`. Section headers are supported, but sometimes one needs a main header for the whole table.

**Comment by nicklockwood** [comment]
If you add a nested <View> inside the table, it should get assigned as the header automatically.

**Comment by algrid** [comment]
@nicklockwood Thank you, it works!

For some reason GitHub search is giving me no results for "tableHeaderView" - that's why I thought it's not implemented.
