### ISSUE TITLE
SamplesApp crashes on Xcode 11 beta 3

### ISSUE THREAD

**Issue by akramhussein** [nicklockwood/layout#178]
XCode version: `Version 11.0 beta 3 (11M362v)`

Couple clicks on Simulator and crashes with nothing more than: 

`libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by akramhussein** [comment]
Sorry, I appreciate this is very vague so let me know if you are need anything else.

Essentially, upon compiling and running on an iPhone Xr simulator with XCode `Version 11.0 beta 3 (11M362v)`, and tapping on a few items on the screen, none of which really respond/lag, it crashes with no useful stack trace.

Upon further testing, it does seem to work but is very slow, in particular scrolling.

**Comment by mgamer** [comment]
Just chiming in with the same issue. It seems quite critical. @nicklockwood do you plan on supporting Layout for iOS 13? We love the library and would gladly use it for our new products (and hopefully provide our own pull requests at some point).

**Comment by akramhussein** [comment]
I concur, this library is so good and while `SwiftUI` may take some wind out of it, we still need to support older iOS versions that `SwiftUI` won't so I can't see us switching away from `Layout` any time soon! I'm happy to support Layout/@nicklockwood through `Github Support` too.

Otherwise, happy to more debugging with a little direction.

**Comment by nicklockwood** [comment]
Sorry for the radio silence. I've not had a chance to look at this yet, but I will definitely make sure Layout is ready for iOS 13 before release.

**Comment by nicklockwood** [comment]
Fixed in 0.6.38

**Comment by sebleclerc** [comment]
I had the same problem in my app using iOS13. Everything is fine now, thanks !
